# Generated by Django 4.2.7 on 2023-12-08 05:00

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Title name"
                    ),
                ),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="work/"),
                ),
                ("about_content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=120, null=True)),
                ("user_image", models.ImageField(upload_to="blog/")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("sub_title", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="blog/")),
                ("second_image", models.ImageField(upload_to="blog/")),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("service_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "service_time",
                    models.CharField(
                        choices=[
                            ("20:00 pm", "8:00 pm"),
                            ("18:00 pm", "6:00 pm"),
                            ("16:00 pm", "4:00 pm"),
                            ("7:00 pm", "7:00 pm"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "services",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("car_towing", "Car Towing"),
                            ("hail_damage", "Hail Damage"),
                            ("car_wash", "Car Wash"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "service_master",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("service_master", "Service Master"),
                            ("micheal", "Micheal"),
                            ("daniel", "Daniel"),
                        ],
                        max_length=120,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("subject", models.CharField(blank=True, max_length=120, null=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "service_image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                ("service_content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "member_image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "member_position",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "about_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("about_content", models.TextField(blank=True, null=True)),
                ("education_content", models.TextField(blank=True, null=True)),
                ("awards_content", models.TextField(blank=True, null=True)),
                ("biography_content", models.TextField(blank=True, null=True)),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("youtube_link", models.URLField(blank=True, null=True)),
                ("instagram_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "testimonial_image",
                    models.ImageField(upload_to="testimonial_image/"),
                ),
                (
                    "testimonial_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=120, null=True)),
                ("testimonial_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Title name"
                    ),
                ),
                ("work_content", models.TextField()),
                ("order_num", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
