# Generated by Django 4.2.7 on 2023-12-14 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "About"},
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Blog"},
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Booking"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Team"},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={"verbose_name": "Testimonial"},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name": "Work"},
        ),
    ]
