# Generated by Django 4.2.7 on 2023-12-14 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_about_options_alter_blog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "About", "verbose_name_plural": "Abouts"},
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Blog", "verbose_name_plural": "Blogs"},
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Booking", "verbose_name_plural": "Bookings"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name": "Work", "verbose_name_plural": "Works"},
        ),
    ]
